### PR TITLE
Token issue

### LINKED ISSUE #204: token issue in distributed setup with ACL
# Summary
If we enable ACL rules for distributed setup, we cannot get correct response from remote server.
In the resolver level, the token is embedded in the `context`. However, currently `context` would not be passed to the model level. So distributed models and relevant remote adapters have no token. Hence, any query to remote server would fail.

A solution: extend model functions to receive the token, and use it in the header of query via axios.

### PR DESCRIPTION
**Pull request by wunderbarr**
close #204

### CODE REVIEW

File: test/testenv_docker_up.sh [hunk 1]
```diff
@@ -57,4 +65,14 @@ for id in ${pids[@]}; do
   wait $id || exit 0
 done
 
+if [[ $OPT_ACL_SETUP == "true" ]]; then
+  UID_GID="$(id -u):$(id -g)" docker-compose \
+    -f "${TEST_DIR}/integration_test_misc/docker-compose-test-acl.yml" restart "gql_science_db_graphql_server2"
```
Comment (coeit) [inline test/testenv_docker_up.sh:70]: maybe add a comment why we restart

**Review by coeit — APPROVED** [review]
